FROM tomcat:11-jdk17

# Create image storage directories
RUN mkdir -p /var/lib/cheeper/images/profiles \
    /var/lib/cheeper/images/defaults \
    /var/lib/cheeper/images/temp

# Copy default profile picture
COPY src/main/webapp/static/images/default.png /var/lib/cheeper/images/defaults/
COPY src/main/webapp/static/images/default.png /var/lib/cheeper/images/profiles/

# backgroundProcessorDelay from 10s to 1s, faster "hot reload" on redeployment of .war
RUN sed -i \
    's/backgroundProcessorDelay="10"/backgroundProcessorDelay="1"/' \
    /usr/local/tomcat/conf/server.xml

# Create ROOT directory and symlink for serving images
RUN mkdir -p /usr/local/tomcat/webapps/ROOT && \
    ln -s /var/lib/cheeper/images /usr/local/tomcat/webapps/ROOT/local-images
